"""Pure-ASGI middlewares wrapped around the whole app.

Pure ASGI (not BaseHTTPMiddleware) on purpose: they must see WebSocket handshakes too
and must never buffer a streaming body. The ORDER is set in app.main.create_app —
read the comment there before adding another.
"""

import asyncio
import errno
import logging
import socket
import time

import asyncpg
from fastapi import HTTPException
from starlette.datastructures import Headers
from starlette.responses import JSONResponse, PlainTextResponse
from starlette.types import ASGIApp, Message, Receive, Scope, Send
from starlette.websockets import WebSocket

from app.config import settings

logger = logging.getLogger(__name__)

# C1 (cross-plan contract): every response this app generates carries this header, so
# the phone can tell an app-level rejection (a real 4xx from a route) from Traefik's own
# 404/502 while bmsmon-api is stopped, starting or unhealthy — which it used to treat as
# "server rejects this batch" and delete the outbox (DATA-14). Traefik never adds it.
API_MARKER_HEADER = "X-Bmsmon-Api"
API_MARKER_VALUE = "1"
_MARKER = (API_MARKER_HEADER.lower().encode("latin-1"), API_MARKER_VALUE.encode("latin-1"))

# DATA-20: the server's clock on every app-generated /api/ response, so the phone can show
# "server clock off by N s" itself (skew = header - phone clock). Not uvicorn's Date: this
# is bmsmon's own clock at ms resolution, also present in tests and through any proxy.
SERVER_TIME_HEADER = "X-Bmsmon-Server-Time-Ms"
_SERVER_TIME = SERVER_TIME_HEADER.lower().encode("latin-1")


def _now_ms() -> str:
    """The X-Bmsmon-Server-Time-Ms value: the server's clock in epoch milliseconds."""
    return str(int(time.time() * 1000))


# Response-start messages: plain HTTP, the WebSocket 101 accept, and a WebSocket denial
# response. A pre-accept websocket.close carries no headers (uvicorn answers it with a
# bare 403), so it cannot be marked — nothing that matters to the phone uses /ws.
_STARTS = frozenset({"http.response.start", "websocket.accept",
                     "websocket.http.response.start"})


class ApiMarkerMiddleware:
    """Stamps X-Bmsmon-Api: 1 on every response start, and X-Bmsmon-Server-Time-Ms on
    every /api/ one. Must stay the OUTERMOST user middleware so responses generated by
    inner middlewares (e.g. the body cap's 413) are marked too."""

    def __init__(self, app: ASGIApp) -> None:
        self.app = app

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] not in ("http", "websocket"):
            await self.app(scope, receive, send)
            return

        stamp_time = scope.get("path", "").startswith("/api/")

        async def send_marked(message: Message) -> None:
            if message["type"] in _STARTS:
                headers = [(k, v) for k, v in (message.get("headers") or [])
                           if k.lower() not in (_MARKER[0], _SERVER_TIME)]
                headers.append(_MARKER)
                if stamp_time:
                    headers.append((_SERVER_TIME, _now_ms().encode("latin-1")))
                message = {**message, "headers": headers}
            await send(message)

        await self.app(scope, receive, send_marked)


_CLOSED_MARKERS = ("pool is closed", "pool is closing", "pool is not initialized", "connection is closed")


# Exceptions that mean "the database cannot be reached or cannot take this right now",
# not "this request is broken". See is_db_unavailable for the per-class reasoning.
_DB_UNAVAILABLE_CLASSES: tuple[type[BaseException], ...] = (
    asyncpg.exceptions.PostgresConnectionError,
    asyncpg.exceptions.TooManyConnectionsError,
    # SQLSTATE class 57 (admin/crash shutdown, cannot connect now, query canceled) and
    # 55P03 (a pg_dump holding a lock): all transient, so err toward a retry, never a
    # skipped row.
    asyncpg.exceptions.OperatorInterventionError,
    asyncpg.exceptions.LockNotAvailableError,
    # SQLSTATE class 53 (disk full, out of memory, too many connections) and 25006 (a
    # read-only standby or a disk-full read-only fallback): the DB is up but cannot take
    # writes. A marked 500 here would read as a deterministic fault and let the phone skip
    # good rows while the DB is sick (DATA-22 review).
    asyncpg.exceptions.InsufficientResourcesError,
    asyncpg.exceptions.ReadOnlySQLTransactionError,
    # Class 58 (the server's own I/O / system errors), 28xxx (credentials no longer
    # accepted, e.g. mid password rotation) and 3D000 (database gone): the DB is unusable
    # for EVERY request, not for this sample. XX000 (internal error) stays a 500.
    asyncpg.exceptions.PostgresSystemError,
    asyncpg.exceptions.InvalidAuthorizationSpecificationError,
    asyncpg.exceptions.InvalidCatalogNameError,
)

# Every class db_error_handler is registered for. InterfaceError and OSError are only
# SOMETIMES an outage (is_db_unavailable decides). asyncio.TimeoutError is the builtin
# TimeoutError on 3.11+, an OSError subclass, so OSError covers it.
DB_ERROR_HANDLED_TYPES: tuple[type[BaseException], ...] = (
    *_DB_UNAVAILABLE_CLASSES, asyncpg.exceptions.InterfaceError, OSError)

# The guest share page's token is in the URL: no response from that zone may be cached or
# leak a Referer, error responses included. routers/share.py uses the same dict.
SHARE_SEC_HEADERS = {"Referrer-Policy": "no-referrer", "Cache-Control": "no-store"}

DB_UNAVAILABLE_LOG_INTERVAL_S = 10.0
WS_INTERNAL_ERROR = 1011  # what uvicorn itself sent on an unhandled websocket error


_NETWORK_ERRNOS = frozenset({errno.ECONNREFUSED, errno.ECONNRESET, errno.EHOSTUNREACH,
                             errno.ENETUNREACH, errno.ETIMEDOUT, errno.EPIPE})


def is_db_unavailable(exc: BaseException) -> bool:
    """True when exc means the database cannot be reached right now (restart, refused
    connection, exhausted or closed pool, acquire timeout) rather than a bug. Such a
    failure is transient, so the phone must retry it instead of treating it as a
    deterministic fault."""
    if isinstance(exc, _DB_UNAVAILABLE_CLASSES):
        return True
    if isinstance(exc, asyncpg.exceptions.InterfaceError):
        msg = str(exc).lower()
        return any(m in msg for m in _CLOSED_MARKERS)
    # Network-shaped errors only. Any other OSError (FileNotFoundError, PermissionError,
    # ENOSPC, ...) is a bug on this host, not a DB outage: it must stay a loud 500.
    if isinstance(exc, (ConnectionError, socket.gaierror, TimeoutError, asyncio.TimeoutError)):
        return True
    return isinstance(exc, OSError) and exc.errno in _NETWORK_ERRNOS


def error_headers(path: str) -> dict[str, str]:
    """Headers every error response built here carries: the C1 marker, plus the share
    zone's no-store/no-referrer on /share/ paths and the server clock on /api/ paths (the
    crash 500 is sent from outside ApiMarkerMiddleware, so it must carry them itself)."""
    headers = {API_MARKER_HEADER: API_MARKER_VALUE}
    if path.startswith("/share/"):
        headers.update(SHARE_SEC_HEADERS)
    if path.startswith("/api/"):
        headers[SERVER_TIME_HEADER] = _now_ms()
    return headers


def _log_db_unavailable(conn, exc: BaseException) -> None:
    """One WARNING per exception class per DB_UNAVAILABLE_LOG_INTERVAL_S, no traceback."""
    name = type(exc).__name__
    throttle = getattr(conn.app.state, "db_unavailable_log", None)
    if throttle is None or throttle.should_touch(name):
        logger.warning("database unavailable (%s) on %s; repeats of %s suppressed for %.0f s",
                       name, conn.url.path, name, DB_UNAVAILABLE_LOG_INTERVAL_S)


def _db_unavailable_response(path: str) -> JSONResponse:
    return JSONResponse({"detail": "database unavailable"}, status_code=503,
                        headers={**error_headers(path), "Retry-After": "30"})


async def db_error_handler(conn, exc: Exception):
    """ExceptionMiddleware handler for DB_ERROR_HANDLED_TYPES. Unlike the catch-all below,
    a response from here is the END of the exception: Starlette does not re-raise it, so
    uvicorn prints no traceback for an outage. An InterfaceError/OSError that is NOT an
    outage is a crash: logged once WITH its traceback here, answered as a marked 500."""
    path = conn.url.path
    outage = is_db_unavailable(exc)
    if outage:
        _log_db_unavailable(conn, exc)
    else:
        logger.error("unhandled %s on %s", type(exc).__name__, path, exc_info=exc)
    if isinstance(conn, WebSocket):
        try:
            await conn.close(code=WS_INTERNAL_ERROR)
        except RuntimeError:
            pass  # the socket is already closed
        return None
    if outage:
        return _db_unavailable_response(path)
    return PlainTextResponse("Internal Server Error", status_code=500, headers=error_headers(path))


async def marked_internal_error(request, exc: Exception):
    """Catch-all handler. Starlette's ServerErrorMiddleware sits OUTSIDE every user
    middleware, so its default 500 never passes ApiMarkerMiddleware; this handler stamps
    the marker itself. Outages normally never get here (db_error_handler answers them
    inside the app); the branch stays as a backstop. Anything else is a marked 500 (a
    crash) whose body matches Starlette's default, and the exception is re-raised after
    the response (uvicorn logs it): crashes keep their traceback."""
    if is_db_unavailable(exc):
        _log_db_unavailable(request, exc)
        return _db_unavailable_response(request.url.path)
    return PlainTextResponse("Internal Server Error", status_code=500,
                             headers=error_headers(request.url.path))


class BodySizeLimitMiddleware:
    """SEC-17 / C4: ONE request-body cap (settings.max_body_bytes) for every HTTP route.

    A declared Content-Length over the cap is refused with 413 before the route (and any
    rate limiter) runs. A body without (or lying about) Content-Length is counted as it
    streams, and the read that crosses the cap raises HTTPException(413), which the
    ExceptionMiddleware turns into the same response. Nothing past the cap is buffered.
    This is what bounds /api/v1/enroll, whose pydantic body FastAPI would otherwise read
    whole, pre-auth. The device routes keep their own caps in _read_body as a second line.
    """

    def __init__(self, app: ASGIApp) -> None:
        self.app = app

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return
        limit = settings.max_body_bytes  # read per request: tests override it
        declared = Headers(scope=scope).get("content-length")
        if declared is not None:
            try:
                too_big = int(declared) > limit
            except ValueError:
                too_big = False  # malformed header: the streamed count below still bounds it
            if too_big:
                response = JSONResponse({"detail": "body too large"}, status_code=413)
                await response(scope, receive, send)
                return
        received = 0

        async def capped_receive() -> Message:
            nonlocal received
            message = await receive()
            if message["type"] == "http.request":
                received += len(message.get("body", b""))
                if received > limit:
                    raise HTTPException(413, "body too large")
            return message

        await self.app(scope, capped_receive, send)
