"""Pure-ASGI middlewares wrapped around the whole app.

Pure ASGI (not BaseHTTPMiddleware) on purpose: they must see WebSocket handshakes too
and must never buffer a streaming body. The ORDER is set in app.main.create_app —
read the comment there before adding another.
"""

from starlette.responses import PlainTextResponse
from starlette.types import ASGIApp, Message, Receive, Scope, Send

# C1 (cross-plan contract): every response this app generates carries this header, so
# the phone can tell an app-level rejection (a real 4xx from a route) from Traefik's own
# 404/502 while bmsmon-api is stopped, starting or unhealthy — which it used to treat as
# "server rejects this batch" and delete the outbox (DATA-14). Traefik never adds it.
API_MARKER_HEADER = "X-Bmsmon-Api"
API_MARKER_VALUE = "1"
_MARKER = (API_MARKER_HEADER.lower().encode("latin-1"), API_MARKER_VALUE.encode("latin-1"))
# Response-start messages: plain HTTP, the WebSocket 101 accept, and a WebSocket denial
# response. A pre-accept websocket.close carries no headers (uvicorn answers it with a
# bare 403), so it cannot be marked — nothing that matters to the phone uses /ws.
_STARTS = frozenset({"http.response.start", "websocket.accept",
                     "websocket.http.response.start"})


class ApiMarkerMiddleware:
    """Stamps X-Bmsmon-Api: 1 on every response start. Must stay the OUTERMOST user
    middleware so responses generated by inner middlewares (e.g. the body cap's 413)
    are marked too."""

    def __init__(self, app: ASGIApp) -> None:
        self.app = app

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] not in ("http", "websocket"):
            await self.app(scope, receive, send)
            return

        async def send_marked(message: Message) -> None:
            if message["type"] in _STARTS:
                headers = [(k, v) for k, v in (message.get("headers") or [])
                           if k.lower() != _MARKER[0]]
                headers.append(_MARKER)
                message = {**message, "headers": headers}
            await send(message)

        await self.app(scope, receive, send_marked)


async def marked_internal_error(request, exc: Exception) -> PlainTextResponse:
    """500 handler. Starlette's ServerErrorMiddleware sits OUTSIDE every user middleware,
    so its default 500 never passes ApiMarkerMiddleware; this handler stamps the marker
    itself. The body matches Starlette's default, and the exception is still re-raised
    (and logged by uvicorn) after this response is sent."""
    return PlainTextResponse("Internal Server Error", status_code=500,
                             headers={API_MARKER_HEADER: API_MARKER_VALUE})
